name: sqlserver-mcp-nuget

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PATH_PROJECT: ./sql-ai/MssqlMcp/dotnet/MssqlMcp/MssqlMcp.csproj
  NUGET_SERVER: https://api.nuget.org/v3/index.json
  SQLSERVER_MCP_REPO: https://github.com/Azure-Samples/SQL-AI-samples.git

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: 8.0.412

      - name: Clonar repositorio com o MCP Server do SQL Server
        run: git clone ${{ env.SQLSERVER_MCP_REPO }} sql-ai

      - name: Exibir conteudos do repositorio clonado
        run: |
          pwd
          ls -l
          echo
          echo
          cd sql-ai
          pwd
          ls -l
          echo
          echo
          cd MssqlMcp/dotnet/MssqlMcp
          pwd
          ls -l
          
      - name: Exibir conteudo do arquivo .csproj antes das alteracoes
        run: cat ${{ env.PATH_PROJECT }}
      
      - name: Alterar o arquivo .csproj para buildar a aplicacao como uma Global Tool
        run: |
          sed -i "/<\/PropertyGroup>/{
            h
            r /dev/stdin
            g
            n
          }" ${{ env.PATH_PROJECT }} <<'EOF'
          
            <PropertyGroup>
              <PackAsTool>true</PackAsTool>
              <ToolCommandName>mcpsqlserver</ToolCommandName>
              <Authors>Renato Groffe</Authors>
              <Company>Groffe</Company>
              <PackageTags>NuGet;.NET;Tool;Sample</PackageTags>
              <Description>
                This tool was generated based on the .NET implementation of the SQL Server MCP Server.
              </Description>
            </PropertyGroup>
          
          EOF

      - name: Exibir conteudo do arquivo .csproj apos as alteracoes
        run: cat ${{ env.PATH_PROJECT }}

      - name: Geracao do package
        run: dotnet pack ${{ env.PATH_PROJECT }} -c Release -o out
      
      - name: Exibir arquivos gerados apos build
        run: |
          cd out
          ls -l
  
      - name: Push no NuGet
        run: |
          cd out
          dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.NUGET_SERVER }}
#          dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.NUGET_SERVER }} --skip-duplicate
